apiVersion: v1
kind: Secret
metadata:
  name: client-auth-token
  labels:
    {{- include "mcCoreCommonConfig.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.clientAuth.token | quote }}
