apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mobilecoind.fullname" . }}
  labels:
    app: mobilecoind
    {{- include "mobilecoind.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mobilecoind
      {{- include "mobilecoind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app: mobilecoind
        {{- include "mobilecoind.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.mobilecoindNodeSelector | nindent 8 }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      initContainers:
      {{- tpl (toYaml .Values.mobilecoind.initContainers) . | nindent 6 }}
      containers:
      - name: mobilecoind
        image: '{{ .Values.mobilecoind.image.org | default .Values.image.org }}/{{ .Values.mobilecoind.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
        imagePullPolicy: Always
        command: [ "/usr/bin/supervisord" ]
        ports:
        - name: mobilecoind-rpc
          containerPort: 3229
        livenessProbe:
          exec:
            command:
            - "/bin/grpc_health_probe"
            - "-addr=:3229"
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - "/bin/grpc_health_probe"
            - "-addr=:3229"
          failureThreshold: 4
          periodSeconds: 30
        env:
        - name: "RUST_BACKTRACE"
          value: "full"
        - name: "RUST_LOG"
          value: "info,rustls=warn,hyper=warn,tokio_reactor=warn,mio=warn,want=warn,reqwest=warn,rusoto_core=error,rusoto_signature=error,h2=error,rocket=warn,<unknown>=warn"
        volumeMounts:
        - name: mobilecoind-data
          mountPath: /mobilecoin
        - name: supervisor-conf
          mountPath: /etc/supervisor/conf.d
          readOnly: true
      volumes:
      - name: mobilecoind-data
        emptyDir: {}
      - name: supervisor-conf
        projected:
          sources:
          - configMap:
              name: {{ include "mobilecoind.fullname" . }}-supervisor-daemon-config
          - configMap:
              name: supervisor-mobilecoind
