apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-fog-ledger-http
  labels:
    app: fog-ledger
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{ toYaml (tpl .Values.fogLedger.ingress.http.annotations . | fromYaml)| nindent 4 }}
spec:
  tls:
  - hosts:
    - {{ include "chart.fogPublicFQDN" . }}
    secretName: {{ include "chart.fogPublicFQDN" . }}-fog-tls
  rules:
  - host: {{ include "chart.fogPublicFQDN" . }}
    http:
      paths:
      - path: /gw/fog_ledger.FogBlockAPI
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" . }}-fog-ledger
            port:
              number: 8228
      - path: /gw/fog_ledger.FogKeyImageAPI
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" . }}-fog-ledger
            port:
              number: 8228
      - path: /gw/fog_ledger.FogMerkleProofAPI
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" . }}-fog-ledger
            port:
              number: 8228
      - path: /gw/fog_ledger.FogUntrustedTxOutApi
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" . }}-fog-ledger
            port:
              number: 8228
