apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fogServices.fullname" . }}-fog-report
  labels:
    app: fog-report
    {{- include "fogServices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fogReport.replicaCount }}
  selector:
    matchLabels:
      app: fog-report
      {{- include "fogServices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.fogReport.podAnnotations | nindent 8 }}
      labels:
        app: fog-report
        {{- include "fogServices.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      initContainers:
      - name: sysctl
        image: ubuntu:20.04
        command:
        - sysctl
        - -w
        - net.ipv4.tcp_retries2=5
        - net.core.somaxconn=65535
        securityContext:
          privileged: true
          runAsUser: 0
          runAsNonRoot: False
      containers:
      - name: fog-report
        image: "{{ .Values.fogReport.image.org | default .Values.image.org }}/{{ .Values.fogReport.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: [ "/usr/bin/supervisord" ]
        ports:
        - name: report
          containerPort: 3222
        - name: mgmt
          containerPort: 8000
        env:
        - name: "RUST_BACKTRACE"
          value: {{ .Values.fogReport.rust.backtrace | quote }}
        - name: "RUST_LOG"
          value: {{ .Values.fogReport.rust.log | quote }}
        - name: "FOG_REPORT_SENTRY_DSN"
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.sentryConfigMapName" . }}
              key: fog-report-sentry-dsn
        # Maps to Sentry Environment
        - name: MC_BRANCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FOGDB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.recoveryDatabaseConfigMapName" . }}
              key: postgresql-hostname
        - name: FOGDB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.recoveryDatabaseConfigMapName" . }}
              key: postgresql-username
        - name: FOGDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fogServices.recoveryDatabaseSecretName" . }}
              key: postgresql-password
        - name: FOGDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.recoveryDatabaseConfigMapName" . }}
              key: postgresql-database
        - name: FOGDB_SSL_OPTIONS
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.recoveryDatabaseConfigMapName" . }}
              key: postgresql-ssl-options
        - name: DATABASE_URL
          value: "postgres://$(FOGDB_USER):$(FOGDB_PASSWORD)@$(FOGDB_HOST)/$(FOGDB_DATABASE)$(FOGDB_SSL_OPTIONS)"
        - name: POSTGRES_IDLE_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.fogReportConfigMapName" . }}
              key: POSTGRES_IDLE_TIMEOUT
        - name: POSTGRES_MAX_LIFETIME
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.fogReportConfigMapName" . }}
              key: POSTGRES_MAX_LIFETIME
        - name: POSTGRES_CONNECTION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.fogReportConfigMapName" . }}
              key: POSTGRES_CONNECTION_TIMEOUT
        - name: POSTGRES_MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: {{ include "fogServices.fogReportConfigMapName" . }}
              key: POSTGRES_MAX_CONNECTIONS
        volumeMounts:
        - name: supervisor-conf
          mountPath: /etc/supervisor/conf.d
          readOnly: true
        - name: signing-cert
          mountPath: /certs
          readOnly: true
        resources:
          {{- toYaml .Values.fogReport.resources | nindent 10 }}
{{- if eq .Values.jaegerTracing.enabled true }}
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5775
            name: zk-compact-trft
            protocol: UDP
          - containerPort: 5778
            name: config-rest
            protocol: TCP
          - containerPort: 6831
            name: jg-compact-trft
            protocol: UDP
          - containerPort: 6832
            name: jg-binary-trft
            protocol: UDP
          - containerPort: 14271
            name: admin-http
            protocol: TCP
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
        args:
          - --reporter.grpc.host-port={{ .Values.jaegerTracing.collector }}
          - --reporter.type=grpc
          - --agent.tags=cluster=undefined,container.name=fog-report,deployment.name={{ include "fogServices.fullname" . }},host.ip=${HOST_IP:},pod.name=${POD_NAME:},pod.namespace={{ .Release.Namespace }}
{{- end }}
      nodeSelector:
        {{- toYaml .Values.fogReport.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.fogReport.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.fogReport.affinity | nindent 8 }}
      volumes:
      - name: signing-cert
        secret:
          secretName: fog-report-signing-cert
      - name: supervisor-conf
        projected:
          sources:
          - configMap:
              name: {{ include "fogServices.fullname" . }}-supervisord-daemon
          - configMap:
              name: {{ include "fogServices.fullname" . }}-supervisord-fog-report
          - configMap:
              name: {{ include "fogServices.fullname" . }}-supervisord-admin
