# Adding a separate ingress for each host so we don't stomp on existing certs.
{{- $hosts := split "\n" (include "chart.fogReportHosts" . | trim) }}
{{- range $hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" $ }}-fog-report-http-{{ . }}
  labels:
    app: fog-report
    {{- include "chart.labels" $ | nindent 4 }}
  annotations:
    {{- toYaml $.Values.fogReport.ingress.http.annotations | nindent 4 }}
spec:
  tls:
  - hosts:
    - {{ . }}
    secretName: {{ . }}-fog-tls
  rules:
  - host: {{ . }}
    http:
      paths:
      - path: /gw/report.ReportAPI
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" $ }}-fog-report
            port:
              number: 8222
---
{{- end }}
