{{- $hosts := splitList "\n" (include "fogServices.fogReportHosts" . | trim) }}
{{- range $hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fogServices.fullname" $ }}-grpc-gateway-{{ . }}
  annotations:
    {{- toYaml $.Values.grpcGateway.ingress.annotations | nindent 4 }}
  labels:
    {{- include "fogServices.labels" $ | nindent 4 }}
spec:
  tls:
  - hosts:
    - {{ . }}
    secretName: {{ . }}-fog-tls
  rules:
  - host: {{ . }}
    http:
      paths:
      - path: /gw
        pathType: Prefix
        backend:
          service:
            name: {{ include "fogServices.fullname" $ }}-grpc-gateway
            port:
              number: 8000
---
{{- end }}
