{{- if eq .Values.grpcGateway.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fogServices.fullname" . }}-grpc-gateway
  labels:
    app: grpc-gateway
    {{- include "fogServices.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: grpc-gateway
    {{- include "fogServices.selectorLabels" . | nindent 4 }}
  ports:
    - name: gateway
      port: 8000
      targetPort: gateway
{{- end }}
