{{- if .Values.fogRecoveryDatabase.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fog-recovery-postgresql
  labels:
    {{- include "fogIngestConfig.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ include "fogIngestConfig.pgPassword" . | quote }}
{{- end }}