{{- if .Values.fogRecoveryDatabase.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fog-recovery-postgresql
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.fogRecoveryDatabase.password | quote }}
{{- end }}