apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-consensus-client
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    client-load-balanced: "true"
    app: consensus-node
  ports:
    - name: cns-client
      port: 3223
      targetPort: cns-client