name: 'helm'
description: 'Run helm commands'
inputs:
  action:
    description: "builtin action to run: (s3-publish, rancher-delete-namespace, rancher-)"
    required: true
  aws_access_key_id:
    description: "aws credential for s3 repo"
    required: false
  aws_secret_access_key:
    description: "aws credential for s3 repo"
    required: false
  aws_default_region:
    description: "aws region for s3 repo"
    required: false
  chart_app_version:
    description: "chart appVersion for publish"
    required: false
  chart_path:
    description: "Path to chart files for publish"
    required: false
  chart_version:
    description: "chart version"
    required: false
  chart_repo:
    description: "url for chart repo"
    required: false
  chart_values:
    description: "values for chart release"
    required: false
  chart_name:
    description: "name of chart in repo"
    required: false
  chart_wait_timeout:
    description: "timeout to wait for resources to be healthy"
    required: false
    default: "20m"
  release_name:
    description: "helm release name"
    required: false
  namespace:
    description: "kubernets namespace"
    required: false
  rancher_project:
    description: "rancher project"
    required: false
    default: "default"
  rancher_token: 
    description: "Rancher Auth Token"
    required: false
  rancher_url:
    description: "Rancher management url"
    required: false
  rancher_cluster:
    description: "Rancher K8s Cluster"
    required: false
  commands:
    description: "shell commands to run"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.commands }}
