apiVersion: v1
kind: Secret
metadata:
  name: fog-report-signing-cert
  labels:
    {{- include "fogServicesConfig.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |-
    {{ .Values.fogReport.signingCert.crt }}
  tls.key: |-
    {{ .Values.fogReport.signingCert.key }}
