# Copyright (c) 2018-2022 The MobileCoin Foundation
{{- if .Values.fogRecoveryDatabaseReader.secret.enabled }}
{{- $pw := (include "fogServicesConfig.pgPassword" .)}}
apiVersion: v1
kind: Secret
metadata:
  name: fog-recovery-postgresql
  labels:
    {{- include "fogServicesConfig.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ $pw | quote }}
  postgresql-password: {{ $pw | quote }}
  replication-password: {{ include "fogServicesConfig.pgReplicationPassword" . | quote }}
{{- end }}