name: mobilecoin-dev-deploy

on: 
  workflow_dispatch:
    inputs:
      cluster:
        description: "Target Cluster"
        type: string
        required: true
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      version:
        description: "Chart Version"
        type: string
        required: true
      delete:
        description: "Delete target namespace"
        type: boolean
        required: false
      reset:
        description: "Reset data in target namespace"
        type: boolean
        required: false

jobs:
  list-values:
    runs-on: self-hosted
    steps:
    - name: values
      run: |
        echo namespace ${{ github.event.inputs.namespace }}
        echo cluster ${{ github.event.inputs.cluster }}
        echo delete ${{ github.event.inputs.delete }}
        echo version ${{ github.event.inputs.version }}

  delete-namespace:
    # start after a successful build or destroy is checked on a dispatch
    if: github.event.inputs.delete == 'true'
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Delete namespace
      uses: ./.github/actions/helm
      with:
        action: rancher-namespace-delete
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}
        # chart_version: ${{ github.events.input.version }}

  reset-dev-env:
    if: github.event.inputs.reset == 'true'
    runs-on: self-hosted
    strategy:
      matrix:
        chart:
        - consensus-node-1
        - consensus-node-2
        - consensus-node-3
        - consensus-node-4
        - consensus-node-5
        # - postgres
        # - fog-ingest-blue
        # - fog-services
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # We don't want to just delete the namespace on every run we need to preserve letsEncrypt certificates due to rate limits.
    # We can delete app charts, postgres and dangling PVCs
    - name: Delete release
      uses: ./.github/actions/helm
      with:
        action: rancher-delete-release
        namespace: ${{ github.event.inputs.namespace }}
        release_name: ${{ matrix.chart }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}

  deploy:
    needs:
    - delete-namespace
    - reset-dev-env
    runs-on: self-hosted
    if: success() || skipped()
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create namespace
      uses: ./.github/actions/helm
      with:
        action: rancher-namespace-create
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}

    # populate data for consensus

    - name: Deploy
      run: echo "Deployment!"
