name: mobilecoin-test

on: 
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      commit_message:
        description: "Commit Message"
        type: string
        required: false

jobs:
  list-values:
    runs-on: self-hosted
    steps:
    - name: values
      run: |
        echo namespace ${{ github.event.inputs.namespace }}
        cat ${GITHUB_EVENT_PATH}

  distribute-fog-accounts:
    if: "! contains(github.event.inputs.commit_message, '[skip-test-distribute-fog-accounts]')"
    runs-on: self-hosted
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Distribute coins to fog accounts
      env:
        NAMESPACE: ${{ github.event.inputs.namespace }}
      run: |
        ./build_artifacts/fog-distribution --sample-data-dir ./sample_data \
          --peer mc://node1.${NAMESPACE}.development.mobilecoin.com:443 \
          --peer mc://node2.${NAMESPACE}.development.mobilecoin.com:443 \
          --peer mc://node3.${NAMESPACE}.development.mobilecoin.com:443 \
          --num-tx-to-send 20

# fog-distribution --sample-data-dir /tmp/sample-data --num-tx-to-send 20 \
#   --peer mc://node1.release-1-2-0-ci-2.development.mobilecoin.com:443 \
#   --peer mc://node2.release-1-2-0-ci-2.development.mobilecoin.com:443 \
#   --peer mc://node3.release-1-2-0-ci-2.development.mobilecoin.com:443


  fog-test-client:
    if: |
      always() &&
      ! contains(github.event.inputs.commit_message, '[skip-test-fog-test-client]') &&
      (needs.distribute-fog-accounts.result == 'success' || needs.distribute-fog-accounts.result == 'skipped')
    runs-on: self-hosted
    needs:
    - distribute-fog-accounts
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run fog-test-client
      env:
        NAMESPACE: ${{ github.event.inputs.namespace }}
      run: |
        ./build_artifacts/test_client \
          --key-dir ./sample_data/fog_keys \
          --consensus mc://node1.${NAMESPACE}.development.mobilecoin.com/ \
          --consensus mc://node2.${NAMESPACE}.development.mobilecoin.com/ \
          --consensus mc://node3.${NAMESPACE}.development.mobilecoin.com/ \
          --num-clients 6 \
          --num-transactions 32 \
          --consensus-wait 300 \
          --transfer-amount 20 \
          --fog-view fog-view://fog.${NAMESPACE}.development.mobilecoin.com:443 \
          --fog-ledger fog-ledger://fog.${NAMESPACE}.development.mobilecoin.com:443

  mobilecoind-integration:
    if: |
      always() &&
      ! contains(github.event.inputs.commit_message, '[skip-test-mobilecoind-integration]') &&
      (needs.distribute-fog-accounts.result == 'success' || needs.distribute-fog-accounts.result == 'skipped')
    runs-on: self-hosted
    container:
      image: python:3.7
    needs:
    - distribute-fog-accounts
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run wallet integration (mobilecoind) tests
      env:
        MOBILECOIND_HOST: mobilecoind.${{ github.event.inputs.namespace }}.development.mobilecoin.com
      run: |
        .internal-ci/util/mobilecoind_integration_test.sh
