name: mobilecoin-dev-update-consensus

on: 
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true

jobs:
  list-values:
    runs-on: [self-hosted, small]
    steps:
    - name: values
      run: |
        echo namespace ${{ github.event.inputs.namespace }}

  setup-environment:
    runs-on: [self-hosted, small]
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Create namespace
      uses: ./.github/actions/helm
      with:
        action: namespace-create
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}

    - name: Generate environment values file
      env:
        IAS_KEY: ${{ secrets.IAS_KEY }}
        IAS_SPID: ${{ secrets.IAS_SPID }}
        LEDGER_AWS_ACCESS_KEY_ID: ${{ secrets.LEDGER_AWS_ACCESS_KEY_ID }}
        LEDGER_AWS_SECRET_ACCESS_KEY: ${{ secrets.LEDGER_AWS_SECRET_ACCESS_KEY }}
        FOG_REPORT_SIGNING_CERT: ${{ secrets.FOG_REPORT_SIGNING_CERT }}
        FOG_REPORT_SIGNING_CERT_KEY: ${{ secrets.FOG_REPORT_SIGNING_CERT_KEY }}
        # CLIENT_AUTH_TOKEN:
        # SENTRY_DSN_CONSENSUS:
        # SENTRY_DSN_LEDGER_DISTRIBUTION:
        # SENTRY_DSN_FOG_INGEST:
        # SENTRY_DSN_FOG_VIEW:
        # SENTRY_DSN_FOG_LEDGER:
        # SENTRY_DSN_FOG_INGEST:
      run: |
        mkdir -p .tmp/values/
        .internal-ci/util/generate_dev_values.sh > .tmp/values/mc-core-dev-env-values.yaml

    - name: Deploy environment setup with block_version=2
      uses: ./.github/actions/helm
      with:
        action: helm-deploy
        chart_repo: https://s3.us-east-2.amazonaws.com/charts.mobilecoin.com/
        chart_name: mc-core-dev-env-setup
        chart_version: ${{ github.event.inputs.version }}
        chart_values: .tmp/values/mc-core-dev-env-values.yaml
        chart_set: |
          --set=global.node.nodeConfig.blockVersion='2'
        release_name: mc-core-dev-env-setup
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}

  consensus-restart:
    needs:
    - setup-environment
    runs-on: [self-hosted, small]
    strategy:
      matrix:
        object_name:
        - deployment.app/consensus-node-1
        - deployment.app/consensus-node-2
        - deployment.app/consensus-node-3
        - deployment.app/consensus-node-4
        - deployment.app/consensus-node-5
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Restart Consensus Nodes
      uses: ./.github/actions/helm
      with:
        action: pod-restart
        object_name: ${{ matrix.object_name }}
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}
