name: mobilecoin-test

on: 
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      ingest_color:
        description: "Fog Ingest blue/green"
        type: string
        required: true
      fog_distribution:
        description: "Run fog-distribution test"
        type: boolean
        required: false
        default: true
      fog_test_client:
        description: "Run fog-test-client test"
        type: boolean
        required: false
        default: true
      mobilecoind_integration:
        description: "Run mobilecoind-integration test"
        type: boolean
        required: false
        default: true

jobs:
  list-values:
    runs-on: [self-hosted, small]
    steps:
    - name: values
      run: |
        echo namespace ${{ github.event.inputs.namespace }}
        cat ${GITHUB_EVENT_PATH}

  fog-distribution:
    if: github.event.inputs.fog_distribution
    runs-on: [self-hosted, small]
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test - fog-distribution
      uses: ./.github/actions/helm
      with:
        action: toolbox-exec
        ingest_color: ${{ github.event.inputs.ingest_color }}
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}
        command: |
          /test/bin/fog-distribution-test.sh

  fog-test-client:
    if: |
      always() &&
      github.event.inputs.fog_test_client && needs.fog-distribution.result != 'failed'
    runs-on: [self-hosted, small]
    needs:
    - fog-distribution
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test - fog-test-client
      uses: ./.github/actions/helm
      with:
        action: toolbox-exec
        ingest_color: ${{ github.event.inputs.ingest_color }}
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}
        command: |
          test_client \
            --key-dir /tmp/sample-data/fog_keys \
            --consensus mc://node1.${{ github.event.inputs.namespace }}.development.mobilecoin.com/ \
            --consensus mc://node2.${{ github.event.inputs.namespace }}.development.mobilecoin.com/ \
            --consensus mc://node3.${{ github.event.inputs.namespace }}.development.mobilecoin.com/ \
            --num-clients 6 \
            --num-transactions 32 \
            --consensus-wait 300 \
            --transfer-amount 20 \
            --fog-view fog-view://fog.${{ github.event.inputs.namespace }}.development.mobilecoin.com:443 \
            --fog-ledger fog-ledger://fog.${{ github.event.inputs.namespace }}.development.mobilecoin.com:443

  mobilecoind-integration:
    if: |
      always() &&
      github.event.inputs.mobilecoind_integration && needs.fog-test-client.result != 'failed'
    runs-on: [self-hosted, small]
    needs:
    - fog-test-client
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test - mobilecoind (Wallet Integration)
      uses: ./.github/actions/helm
      with:
        action: toolbox-exec
        ingest_color: ${{ github.event.inputs.ingest_color }}
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}
        command: |
          /test/bin/mobilecoind-integration-test.sh
