name: mobilecoin-dev-green-upgrade

on: 
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      version:
        description: "Chart Version"
        type: string
        required: true

jobs:
  list-values:
    runs-on: self-hosted
    steps:
    - name: values
      run: |
        echo namespace ${{ github.event.inputs.namespace }}
        echo version ${{ github.event.inputs.version }}
