name: mobilecoin-deploy

on:
  workflow_run:
    workflows:
    - mobilecoin-build
    types:
    - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      run: echo "Deployment!"
