name: mobilecoin-dev-reset

on: 
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true

jobs:
  list-values:
    runs-on: ubuntu-latest
    steps:
    - name: values
      run: |
        echo namespace ${{ github.event.inputs.namespace }}

  reset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
        - consensus-node-1
        - consensus-node-2
        - consensus-node-3
        - consensus-node-4
        - consensus-node-5
        - fog-ingest-blue
        - fog-ingest-green
        - fog-recovery-postgresql
        - fog-services
        - mobilecoind
    steps:
    - name: Clean up Workspace
      run: |
        find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    # We don't want to just delete the namespace on every run we need to preserve letsEncrypt certificates due to rate limits.
    # We can delete app charts, postgres and dangling PVCs
    - name: Delete release
      uses: ./.github/actions/helm
      with:
        action: delete-release
        namespace: ${{ github.event.inputs.namespace }}
        release_name: ${{ matrix.chart }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}

  reset-storage:
    needs:
    - reset
    runs-on: ubuntu-latest
    steps:
    - name: Start with clean workspace
      run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: Checkout
      uses: actions/checkout@v2

    # We don't want to just delete the namespace on every run we need to preserve letsEncrypt certificates due to rate limits.
    # We can delete app charts, postgres and dangling PVCs
    - name: Delete PersistentVolumeClaims
      uses: ./.github/actions/helm
      with:
        action: delete-pvcs
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}

  reset-s3:
    needs:
    - reset
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli:latest
    steps:
    - name: Clear out s3 bucket objects
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.LEDGER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.LEDGER_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-central-1
        BUCKET: mobilecoin.eu.development.chain
        NAMESPACE: ${{ github.event.inputs.namespace }}
      run: |
        aws s3 rm --only-show-errors --recursive s3://${BUCKET}/node1.${NAMESPACE}.development.mobilecoin.com
        aws s3 rm --only-show-errors --recursive s3://${BUCKET}/node2.${NAMESPACE}.development.mobilecoin.com
        aws s3 rm --only-show-errors --recursive s3://${BUCKET}/node3.${NAMESPACE}.development.mobilecoin.com
        aws s3 rm --only-show-errors --recursive s3://${BUCKET}/node4.${NAMESPACE}.development.mobilecoin.com
        aws s3 rm --only-show-errors --recursive s3://${BUCKET}/node5.${NAMESPACE}.development.mobilecoin.com
