name: mobilecoin-dev-deploy

on: 
  workflow_dispatch:
    inputs:
      cluster:
        description: "Target Cluster"
        type: string
        required: true
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      version:
        description: "Chart Version"
        type: string
        required: true
      delete:
        description: "Delete target namespace before deploying"
        type: boolean
        required: false

jobs:
  destroy:
    # start after a successful build or destroy is checked on a dispatch
    if: github.events.inputs.delete
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Generate version metadata
    #   id: meta
    #   run: |
    #     .github/workflows/helpers/metadata.sh

    - name: Delete namespace
      uses: ./.github/actions/helm
      with:
        action: rancher-delete-namespace
        namespace: ${{ github.events.input.branch }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}

  deploy:
    runs-on: self-hosted
    needs:
    - destroy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      run: echo "Deployment!"
