name: mobilecoin-dispatch-dev-reset

on: 
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true

jobs:
  reset:
    uses: ./.github/reusable-workflows/mobilecoin-workflow-dev-reset.yaml
    with:
      namespace: ${{ github.event.inputs.namespace }}
    secrets:
      RANCHER_CLUSTER: ${{ secrets.RANCHER_CLUSTER }}
      RANCHER_URL: ${{ secrets.RANCHER_URL }}
      RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
      LEDGER_AWS_ACCESS_KEY_ID: ${{ secrets.LEDGER_AWS_ACCESS_KEY_ID }}
      LEDGER_AWS_SECRET_ACCESS_KEY: ${{ secrets.LEDGER_AWS_SECRET_ACCESS_KEY }}
