name: mobilecoin-dispatch-dev-test

on: 
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      ingest_color:
        description: "Fog Ingest blue/green"
        type: string
        required: true
        default: blue
      fog_distribution:
        description: "Run fog-distribution test"
        type: boolean
        required: false
        default: true
      fog_test_client:
        description: "Run fog-test-client test"
        type: boolean
        required: false
        default: true
      mobilecoind_integration:
        description: "Run mobilecoind-integration test"
        type: boolean
        required: false
        default: true

jobs:
  generate-metadata:
    uses: ./.github/workflows/mobilecoin-workflow-dev-generate-metadata.yaml

  previous-release-test:
    needs:
    - generate-metadata
    uses: ./.github/workflows/mobilecoin-workflow-dev-test.yaml
    with:
      namespace: ${{ github.event.inputs.namespace }}
      ingest_color: ${{ github.event.inputs.ingest_color }}
      fog_distribution: ${{ github.event.inputs.fog_distribution == 'true' && 'true' || 'false' }}
      fog_test_client: ${{ github.event.inputs.fog_test_client == 'true' && 'true' || 'false' }}
      mobilecoind_integration: ${{ github.event.inputs.fog_test_client == 'true' && 'true' || 'false' }}
    secrets:
      RANCHER_CLUSTER: ${{ secrets.RANCHER_CLUSTER }}
      RANCHER_URL: ${{ secrets.RANCHER_URL }}
      RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
      FOG_AUTHORITY_ROOT_CA_CERT: ${{ secrets.FOG_AUTHORITY_ROOT_CA_CERT }}
