# Copyright (c) 2018-2022 The MobileCoin Foundation
#
# MobileCoin Core projects - Delete development namespaces when branch is removed.

name: mobilecoin-dev-delete

on:
  delete: {}

jobs:
  list:
    runs-on: [self-hosted, Linux, small]
    steps:
    - name: dump payload
      run: |
        echo '${{ github.event }}'
    - name: details
      run: |
        echo "ref ${{ github.ref }}'
        echo "ref_type ${{ github.ref_type }}"
        echo "ref_name ${{ github.ref_name }}"
  # delete:
  #   if: startsWith(github.ref, 'refs/branch/feature/')
  #   runs-on: [self-hosted, Linux, small]
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Generate version metadata
  #     id: meta
  #     run: |
  #       .internal-ci/util/metadata.sh

  #   - name: Delete branch namespace
  #     uses: mobilecoinofficial/gha-workflow-dispatch@v2.1.3
  #     with:
  #       workflow: mobilecoin-dispatch-dev-delete
  #       token: ${{ secrets.ACTIONS_TOKEN }}
  #       wait-for-completion: true
  #       wait-for-completion-timeout: 30m
  #       wait-for-completion-interval: 30s
  #       display-workflow-run-url-interval: 30s
  #       inputs: |
  #         {
  #           "namespace": "${{ steps.meta.outputs.namespace }}"
  #         }
