name: mobilecoin-dev-deploy

on: 
  workflow_dispatch:
    inputs:
      cluster:
        description: "Target Cluster"
        type: string
        required: true
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      version:
        description: "Chart Version"
        type: string
        required: true
      delete:
        description: "Delete target namespace before deploying"
        type: boolean
        required: false

jobs:
  list-values:
    runs-on: self-hosted
    steps:
    - name: values
      run: |
        echo namespace ${{ github.event.inputs.namespace }}
        echo cluster ${{ github.event.inputs.cluster }}
        echo delete ${{ github.event.inputs.delete }}
        echo version ${{ github.event.inputs.version }}

  destroy:
    # start after a successful build or destroy is checked on a dispatch
    if: github.event.inputs.delete == 'true'
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Delete namespace
      uses: ./.github/actions/helm
      with:
        action: rancher-namespace-delete
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}
        # chart_version: ${{ github.events.input.version }}

  deploy:
    needs:
    - destroy
    if: needs.destroy.result == 'success' || needs.destroy.result == 'skipped'
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create namespace
      uses: ./.github/actions/helm
      with:
        action: rancher-namespace-create
        namespace: ${{ github.event.inputs.namespace }}
        rancher_cluster: ${{ secrets.RANCHER_CLUSTER }}
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}

    # populate data for consensus

    - name: Deploy
      run: echo "Deployment!"
