apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-supervisord-daemon
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  supervisor.conf: |
    [supervisord]
    nodaemon=true
