apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fogIngest.fullname" . }}-toolbox
  labels:
    {{- include "fogIngest.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
      {{- include "fogIngest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: toolbox
        {{- include "fogIngest.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      containers:
      - image: '{{ .Values.toolbox.image.org | default .Values.image.org }}/{{ .Values.toolbox.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
        name: toolbox
        args:
        - /bin/cat
        tty: true
        env:
        - name: FOGDB_HOST
          valueFrom:
            configMapKeyRef:
              name: fog-recovery-postgresql
              key: postgresql-hostname
        - name: FOGDB_USER
          valueFrom:
            configMapKeyRef:
              name: fog-recovery-postgresql
              key: postgresql-username
        - name: FOGDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fog-recovery-postgresql
              key: postgresql-password
        - name: FOGDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: fog-recovery-postgresql
              key: postgresql-database
        - name: FOGDB_SSL_OPTIONS
          valueFrom:
            configMapKeyRef:
              name: fog-recovery-postgresql
              key: postgresql-ssl-options
        - name: DATABASE_URL
          value: 'postgres://$(FOGDB_USER):$(FOGDB_PASSWORD)@$(FOGDB_HOST)/$(FOGDB_DATABASE)$(FOGDB_SSL_OPTIONS)'
        volumeMounts:
        - name: sample-data
          mountPath: /sample-data
      nodeSelector:
        {{- toYaml .Values.toolbox.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.toolbox.tolerations | nindent 8 }}
      volumes:
      - name: sample-data
        projected:
          sources:
          - secret:
              name: sample-keys
              optional: true
          - secret:
              name: sample-keys-fog
              optional: true
